import os

folders = [
    "frontend/src/app",
    "frontend/src/providers",
    "frontend/src/modules",
    "frontend/src/routes",
    "frontend/src/styles",
    "frontend/src/assets/images",
    "frontend/src/assets/icons",
    "frontend/src/components/ui",
    "frontend/src/components/dashboard",
    "frontend/src/components/landing",
    "frontend/src/components/analytics",
    "frontend/src/components/interview",
    "frontend/src/components/coding",
    "frontend/src/components/resume",
    "frontend/src/components/shared",
    "frontend/src/components/feedback",
    "frontend/src/lib",
    "backend/src/config",
    "backend/src/controllers",
    "backend/src/routes",
    "backend/src/middleware",
    "backend/src/models",
    "backend/src/services",
    "backend/src/validators",
    "backend/src/sockets",
    "backend/src/utils",
    "backend/src/jobs",
    "backend/src/types",
    "backend/src/interfaces",
    "backend/src/constants",
    "backend/src/database",
    "backend/src/cache",
    "backend/src/logs",
    "backend/src/tests",
    "ai-service/routes",
    "ai-service/services",
    "ai-service/prompts",
    "ai-service/evaluators",
    "ai-service/parsers",
    "ai-service/pipelines",
    "ai-service/models",
    "ai-service/utils",
    "ai-service/config",
    "ai-service/schemas",
    "ai-service/vectorstore",
    "ai-service/embeddings",
    "ai-service/rag",
    "ai-service/tests",
    "ai-service/logs",
    "docs",
    "docker",
    "screenshots",
    "scripts",
    ".github/workflows"
]

for folder in folders:
    os.makedirs(folder, exist_ok=True)
    print(f"Created {folder}")
